### ISSUE TITLE
支付回调验证签名报错

### ISSUE THREAD

**Issue by Tmamasay** [klover2/wechatpay-node-v3-ts#18]
错误描述：Error: Unsupported state or unable to authenticate data
2022-04-15 09:51:29,428 ERROR 4860 [-/::ffff:127.0.0.1/-/242ms POST /api/orderCallback] Error: Unsupported state or unable to authenticate data
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at Pay.decipher_gcm (D:\haocuan\midway_mon\node_modules\wechatpay-node-v3\dist\index.js:396:14)
    at D:\haocuan\midway_mon\node_modules\wechatpay-node-v3\dist\index.js:208:50
    at Array.forEach (<anonymous>)
    at Pay.<anonymous> (D:\haocuan\midway_mon\node_modules\wechatpay-node-v3\dist\index.js:207:20)
    at step (D:\haocuan\midway_mon\node_modules\wechatpay-node-v3\dist\index.js:139:21)
    at Object.next (D:\haocuan\midway_mon\node_modules\wechatpay-node-v3\dist\index.js:76:16)
    at fulfilled (D:\haocuan\midway_mon\node_modules\wechatpay-node-v3\dist\index.js:30:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

好像是解析不了数据，请教下如何处理这种问题

**Comment by klover2** [comment]
> 

请问你参数是不是弄错了，这个签名已经很久没有改过了

**Comment by Tmamasay** [comment]
![image](https://user-images.githubusercontent.com/31384364/163528328-58417ed3-2b8d-4ab6-a70c-879a1a92aea5.png)
参数应该是没有错

**Comment by Tmamasay** [comment]
![image](https://user-images.githubusercontent.com/31384364/163531939-3a88f069-7ec5-4cfe-82fc-d7f216dd54c2.png)
我这里读取出来的数据是乱码的

**Comment by klover2** [comment]
![image](https://user-images.githubusercontent.com/49548817/163745820-7e1958a4-9e64-4776-8bf3-34fc9925d518.png)
你调用参数是怎样的

**Comment by Tmamasay** [comment]
![image](https://user-images.githubusercontent.com/31384364/163760183-7a59bf44-b2f6-4818-a30a-a96ad18e0000.png)
密钥key可以用，有其他语言的项目也在用这个key

**Comment by Tmamasay** [comment]
sorry，是密钥key的问题，我们v2，v3的Key不一样，我重置就可以了
