### ISSUE TITLE
退款接口报错

### ISSUE THREAD

**Issue by devoutDisciple** [klover2/wechatpay-node-v3-ts#19]
调用refunds退款接口的时候报错：
TypeError: Cannot read property 'text' of null
    at Pay.<anonymous> (/Users/zhangzhen/baomu/baomu_frontBack/node_modules/wechatpay-node-v3/dist/index.js:226:98)
    at step (/Users/zhangzhen/baomu/baomu_frontBack/node_modules/wechatpay-node-v3/dist/index.js:44:23)
    at Object.throw (/Users/zhangzhen/baomu/baomu_frontBack/node_modules/wechatpay-node-v3/dist/index.js:25:53)
    at rejected (/Users/zhangzhen/baomu/baomu_frontBack/node_modules/wechatpay-node-v3/dist/index.js:17:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

调用参数：
{"transaction_id":"420xxxxxxx877351","out_refund_no":"BJY1Exxxxxxxxxx47949","notify_url":"https://www.baidu.com/xxxxxxx/xxxxxxx","amount":{"refund":20,"total":20,"currency":"CNY"}}

这个错误好像是偶发的，不知道什么原因

**Comment by klover2** [comment]
> 调用refunds退款接口的时候报错： TypeError: Cannot read property 'text' of null at Pay. (/Users/zhangzhen/baomu/baomu_frontBack/node_modules/wechatpay-node-v3/dist/index.js:226:98) at step (/Users/zhangzhen/baomu/baomu_frontBack/node_modules/wechatpay-node-v3/dist/index.js:44:23) at Object.throw (/Users/zhangzhen/baomu/baomu_frontBack/node_modules/wechatpay-node-v3/dist/index.js:25:53) at rejected (/Users/zhangzhen/baomu/baomu_frontBack/node_modules/wechatpay-node-v3/dist/index.js:17:65) at processTicksAndRejections (internal/process/task_queues.js:95:5)
> 
> 调用参数： {"transaction_id":"420xxxxxxx877351","out_refund_no":"BJY1Exxxxxxxxxx47949","notify_url":"[https://www.baidu.com/xxxxxxx/xxxxxxx","amount":{"refund":20,"total":20,"currency":"CNY"}}](https://www.baidu.com/xxxxxxx/xxxxxxx%22,%22amount%22:%7B%22refund%22:20,%22total%22:20,%22currency%22:%22CNY%22%7D%7D)
> 
> 这个错误好像是偶发的，不知道什么原因
你用的npm 包是那个版本的，这个问题有点像之前 superagent 请求报错，后面在1.3.3里加上了请求头 'Accept-Encoding': 'gzip' 就好了
