### ISSUE TITLE
`transactions_native` 报错信息处理异常 Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by waveiron** [klover2/wechatpay-node-v3-ts#45]
```text
TypeError: Cannot read properties of undefined (reading 'text')
    at Pay.<anonymous> (/root/node_modules/wechatpay-node-v3/dist/lib/base.js:105:94)
    at step (/root/node_modules/wechatpay-node-v3/dist/lib/base.js:44:23)
    at Object.throw (/root/node_modules/wechatpay-node-v3/dist/lib/base.js:25:53)
    at rejected (/root/node_modules/wechatpay-node-v3/dist/lib/base.js:17:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

有可能是 `err.response` 空值的问题：

<img width="912" alt="image" src="https://user-images.githubusercontent.com/4930447/227560523-b82bd1c0-6613-44af-a060-41bedc42b033.png">

**Comment by klover2** [comment]
正常来说 应该是你参数错了 才会触发这种异常报错

**Comment by WanGe2000** [comment]
> 正常来说 应该是你参数错了 才会触发这种异常报错

具体是什么参数呢？我也碰到了这个问题

**Comment by klover2** [comment]
> > 正常来说 应该是你参数错了 才会触发这种异常报错
> 
> 具体是什么参数呢？我也碰到了这个问题，该传的参数都传了

请看最新版本 2.1.4 兼容了空值问题

**Comment by WanGe2000** [comment]
> > > 正常来说 应该是你参数错了 才会触发这种异常报错
> > 
> > 
> > 具体是什么参数呢？我也碰到了这个问题，该传的参数都传了
> 
> 请看最新版本 2.1.4 兼容了空值问题

好的，感谢
