### ISSUE TITLE
调用回调解密方法decipher_gcm时报错缺少key

### ISSUE THREAD

**Issue by ngnwg** [klover2/wechatpay-node-v3-ts#64]
/root/wechat/wechat-server/node_modules/wechatpay-node-v3/dist/index.js:323
            throw new Error('缺少key');
                  ^

Error: 缺少key
    at Pay.decipher_gcm (/root/wechat/wechat-server/node_modules/wechatpay-node-v3/dist/index.js:323:19)
    at /root/wechat/wechat-server/node_modules/wechatpay-node-v3/dist/index.js:162:64
    at Array.forEach (<anonymous>)
    at Pay.<anonymous> (/root/wechat/wechat-server/node_modules/wechatpay-node-v3/dist/index.js:161:34)
    at step (/root/wechat/wechat-server/node_modules/wechatpay-node-v3/dist/index.js:59:23)
    at Object.next (/root/wechat/wechat-server/node_modules/wechatpay-node-v3/dist/index.js:40:53)
    at fulfilled (/root/wechat/wechat-server/node_modules/wechatpay-node-v3/dist/index.js:31:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by klover2** [comment]
> /root/wechat/wechat-server/node_modules/wechatpay-node-v3/dist/index.js:323 throw new Error('缺少key'); ^
> 
> Error: 缺少key at Pay.decipher_gcm (/root/wechat/wechat-server/node_modules/wechatpay-node-v3/dist/index.js:323:19) at /root/wechat/wechat-server/node_modules/wechatpay-node-v3/dist/index.js:162:64 at Array.forEach () at Pay. (/root/wechat/wechat-server/node_modules/wechatpay-node-v3/dist/index.js:161:34) at step (/root/wechat/wechat-server/node_modules/wechatpay-node-v3/dist/index.js:59:23) at Object.next (/root/wechat/wechat-server/node_modules/wechatpay-node-v3/dist/index.js:40:53) at fulfilled (/root/wechat/wechat-server/node_modules/wechatpay-node-v3/dist/index.js:31:58) at processTicksAndRejections (node:internal/process/task_queues:96:5)

请使用版本2.1.8 同时检查你的key 是否传了

![image](https://github.com/klover2/wechatpay-node-v3-ts/assets/49548817/15554ed2-a0d7-4c5f-8ab5-7acc0ca7e7e0)
