### ISSUE TITLE
pay.verifySign(params) 验证签名报错: 平台证书序列号不相符，未找到平台序列号

### ISSUE THREAD

**Issue by louisyonge** [klover2/wechatpay-node-v3-ts#73]
用的是2.1.8版本的sdk，证书是微信申请的免费证书。可以正常用代码下单。支付成功，回调，验证时报错 
 "errorType": "Error",
    "errorMessage": "平台证书序列号不相符，未找到平台序列号",
    "stack": [
        "Error: 平台证书序列号不相符，未找到平台序列号",
        "    at Pay.<anonymous> (/opt/nodejs/node_modules/wechatpay-node-v3/dist/index.js:200:35)",
        "    at step (/opt/nodejs/node_modules/wechatpay-node-v3/dist/index.js:59:23)",
        "    at Object.next (/opt/nodejs/node_modules/wechatpay-node-v3/dist/index.js:40:53)",
        "    at fulfilled (/opt/nodejs/node_modules/wechatpay-node-v3/dist/index.js:31:58)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
    ]

**Comment by chenadian1** [comment]
我也遇到这个 后面发现是在微信支付的验证微信支付身份中，你申请了微信支付公钥
，就没办法使用了，把微信支付公钥给停止，就可以了

**Comment by lzw10168** [comment]
> 我也遇到这个 后面发现是在微信支付的验证微信支付身份中，你申请了微信支付公钥 ，就没办法使用了，把微信支付公钥给停止，就可以了

谢谢你, 找了我好久的问题. 炸了.
