### ISSUE TITLE
Create T3 App项目中调用方法报错

### ISSUE THREAD

**Issue by ss707494** [klover2/wechatpay-node-v3-ts#82]
`TypeError: hexoid is not a function
at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/formidable@2.1.2/node_modules/formidable/src/Formidable.js:15:18)
at (rsc)/./node_modules/.pnpm/formidable@2.1.2/node_modules/formidable/src/Formidable.js (...\t3-next\.next\server\vendor-chunks\formidable@2.1.2.js:20:1)
at __webpack_require__ (...\t3-next\.next\server\webpack-runtime.js:33:43)
at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/formidable@2.1.2/node_modules/formidable/src/index.js:5:20)
at (rsc)/./node_modules/.pnpm/formidable@2.1.2/node_modules/formidable/src/index.js (...\t3-next\.next\server\vendor-chunks\formidable@2.1.2.js:63:1)
at __webpack_require__ (...\t3-next\.next\server\webpack-runtime.js:33:43)
at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/superagent@8.1.2/node_modules/superagent/lib/node/index.js:29:20)
at (rsc)/./node_modules/.pnpm/superagent@8.1.2/node_modules/superagent/lib/node/index.js (...\t3-next\.next\server\vendor-chunks\superagent@8.1.2.js:50:1)
at __webpack_require__ 
`
这个是我的调用方法
`import fs from "node:fs";
import WxPay from "wechatpay-node-v3";

const pay = new WxPay({
  appid: "***",
  mchid: "***",
  publicKey: fs.readFileSync("./cert/apiclient_cert.pem"), // 公钥
  privateKey: fs.readFileSync("./cert/apiclient_key.pem"), // 秘钥
});

export const payNative = async () => {
  try {

    const params = {
      description: "测试",
      out_trade_no: "***",
      notify_url: "https://www.weixin.qq.com/wxpay/pay.php",
      amount: {
        total: 1,
      },
      scene_info: {
        payer_client_ip: "ip",
      },
    };

    const result = await pay.transactions_native(params);
    console.log(result);
  } catch (error) {
    console.error(error);
  }
  // # { status: 200, code_url: 'weixin://wxpay/bizpayurl?pr=9xFPmlUzz' }
};
`

**Comment by klover2** [comment]
> ```
> TypeError: hexoid is not a function
> at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/formidable@2.1.2/node_modules/formidable/src/Formidable.js:15:18)
> at (rsc)/./node_modules/.pnpm/formidable@2.1.2/node_modules/formidable/src/Formidable.js (...\t3-next\.next\server\vendor-chunks\formidable@2.1.2.js:20:1)
> at __webpack_require__ (...\t3-next\.next\server\webpack-runtime.js:33:43)
> at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/formidable@2.1.2/node_modules/formidable/src/index.js:5:20)
> at (rsc)/./node_modules/.pnpm/formidable@2.1.2/node_modules/formidable/src/index.js (...\t3-next\.next\server\vendor-chunks\formidable@2.1.2.js:63:1)
> at __webpack_require__ (...\t3-next\.next\server\webpack-runtime.js:33:43)
> at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/superagent@8.1.2/node_modules/superagent/lib/node/index.js:29:20)
> at (rsc)/./node_modules/.pnpm/superagent@8.1.2/node_modules/superagent/lib/node/index.js (...\t3-next\.next\server\vendor-chunks\superagent@8.1.2.js:50:1)
> at __webpack_require__ 
> ```
> 
> 这个是我的调用方法
> 
> ```
> 
> import fs from "node:fs";
> import WxPay from "wechatpay-node-v3";
> 
> const pay = new WxPay({
>   appid: "***",
>   mchid: "***",
>   publicKey: fs.readFileSync("./cert/apiclient_cert.pem"), // 公钥
>   privateKey: fs.readFileSync("./cert/apiclient_key.pem"), // 秘钥
> });
> 
> export const payNative = async () => {
>   try {
> 
>     const params = {
>       description: "测试",
>       out_trade_no: "***",
>       notify_url: "https://www.weixin.qq.com/wxpay/pay.php",
>       amount: {
>         total: 1,
>       },
>       scene_info: {
>         payer_client_ip: "ip",
>       },
>     };
> 
>     const result = await pay.transactions_native(params);
>     console.log(result);
>   } catch (error) {
>     console.error(error);
>   }
>   // # { status: 200, code_url: 'weixin://wxpay/bizpayurl?pr=9xFPmlUzz' }
> };
> ```

你指定一下superagent的版本 npm install superagent@8.0.6 看下可以吗

**Comment by airbai** [comment]
报一样的错误：
@fly/nextjs:dev:  ✓ Compiled /api/trpc/edge/[trpc] in 3.4s (6307 modules)
@fly/nextjs:dev:  ⨯ TypeError: hexoid is not a function
@fly/nextjs:dev:     at eval (webpack-internal:///(rsc)/../../node_modules/formidable/src/Formidable.js:15:18)
@fly/nextjs:dev:     at (rsc)/../../node_modules/formidable/src/Formidable.js (/Users/b/Downloads/quanse/ai/fiit/saasfly/apps/nextjs/.next/server/vendor-chunks/formidable.js:20:1)
@fly/nextjs:dev:     at __webpack_require__ (/Users/b/Downloads/quanse/ai/fiit/saasfly/apps/nextjs/.next/server/webpack-runtime.js:33:43)
@fly/nextjs:dev:     at eval (webpack-internal:///(rsc)/../../node_modules/formidable/src/index.js:5:20)
@fly/nextjs:dev:     at (rsc)/../../node_modules/formidable/src/index.js (/Users/b/Downloads/quanse/ai/fiit/fly/apps/nextjs/.next/server/vendor-chunks/formidable.js:63:1)

**Comment by airbai** [comment]
> ```
> TypeError: hexoid is not a function
> at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/formidable@2.1.2/node_modules/formidable/src/Formidable.js:15:18)
> at (rsc)/./node_modules/.pnpm/formidable@2.1.2/node_modules/formidable/src/Formidable.js (...\t3-next\.next\server\vendor-chunks\formidable@2.1.2.js:20:1)
> at __webpack_require__ (...\t3-next\.next\server\webpack-runtime.js:33:43)
> at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/formidable@2.1.2/node_modules/formidable/src/index.js:5:20)
> at (rsc)/./node_modules/.pnpm/formidable@2.1.2/node_modules/formidable/src/index.js (...\t3-next\.next\server\vendor-chunks\formidable@2.1.2.js:63:1)
> at __webpack_require__ (...\t3-next\.next\server\webpack-runtime.js:33:43)
> at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/superagent@8.1.2/node_modules/superagent/lib/node/index.js:29:20)
> at (rsc)/./node_modules/.pnpm/superagent@8.1.2/node_modules/superagent/lib/node/index.js (...\t3-next\.next\server\vendor-chunks\superagent@8.1.2.js:50:1)
> at __webpack_require__ 
> ```
> 
> 这个是我的调用方法
> 
> ```
> 
> import fs from "node:fs";
> import WxPay from "wechatpay-node-v3";
> 
> const pay = new WxPay({
>   appid: "***",
>   mchid: "***",
>   publicKey: fs.readFileSync("./cert/apiclient_cert.pem"), // 公钥
>   privateKey: fs.readFileSync("./cert/apiclient_key.pem"), // 秘钥
> });
> 
> export const payNative = async () => {
>   try {
> 
>     const params = {
>       description: "测试",
>       out_trade_no: "***",
>       notify_url: "https://www.weixin.qq.com/wxpay/pay.php",
>       amount: {
>         total: 1,
>       },
>       scene_info: {
>         payer_client_ip: "ip",
>       },
>     };
> 
>     const result = await pay.transactions_native(params);
>     console.log(result);
>   } catch (error) {
>     console.error(error);
>   }
>   // # { status: 200, code_url: 'weixin://wxpay/bizpayurl?pr=9xFPmlUzz' }
> };
> ```

解决了吗？怎么解读的

**Comment by georgezouq** [comment]
请问 解决了吗？我在 nextjs 15 上 还有这个问题 @airbai  @ss707494 @klover2

**Comment by HenryOoO** [comment]
> 请问 解决了吗？我在 nextjs 15 上 还有这个问题 [@airbai](https://github.com/airbai) [@ss707494](https://github.com/ss707494) [@klover2](https://github.com/klover2)

应该是 trubopack 的兼容性问题，我的解决办法是要么去除 --turbopack， 要么在 nextConfig 里声明
 ```typescript
const nextConfig: NextConfig = {
    serverExternalPackages: ['wechatpay-node-v3', 'formidable', 'superagent'],
}
```
